# test in python
language: python
# python versions tested
python:
  - "3.5"
  - "3.6"
# enable the use of sudo
sudo: required
# set os
os: linux
# set distribution
dist: trusty
# set environment variables
env:
  - PACKAGE_VERSION=0.0.1
# install dependencies
install:
  - pip install -r requirements/dev.txt
# launch test discovery and run tests
script:
  - nose2
# send results to coveralls.io
after_success:
  coveralls
# never give email notifications
notifications:
  on_success: never
  on_failure: never
